### ISSUE TITLE
Any 'u' character present in the code causes a SyntaxError

### ISSUE THREAD

**Issue by katedickey** [IceCreamYou/Chrome-BigConsole#12]
If any character in the code panel is a 'u', the console will show a "SyntaxError: Invalid Unicode escape sequence". 
![image](https://cloud.githubusercontent.com/assets/5097527/17677662/d31e713c-6301-11e6-98b2-f1f3eae88db1.png)

**Comment by IceCreamYou** [comment]
The actual problem is text that matches the regex `\u[0-9a-f]{1,6}`. BigConsole uses this regular expression to escape unicode sequences so that `'\\u00A9'` evaluates to `'\u00A9'` instead of `'\©'` but `'\u00A9'` evaluates to `'©'`. Unfortunately, something seems to have changed in Chrome recently that is causing the error you encountered as well as unexpected escaping of valid sequences (for example `'u00A9'` evaluates to `'©'`).

I have fixed it and will release v1.2.2 with the change.

**Comment by IceCreamYou** [comment]
v1.2.2 is now published and should appear in the Chrome Web Store some time in the next hour. If you have the extension enabled it should update automatically. Thanks for your feedback.
